---
- hosts: localhost
  connection: local
  tasks:
    - name: "create ec2 instances"
      amazon.aws.ec2_instance:
        name: "{{ item.name }}"
        instance_type: t2.micro
        security_group: default
        key_name: "ansible-key-pai"
        access_key: "{{ ec2_access_key }}"
        secret_key: "{{ ec2_secret_key }}"
        region: us-east-1
        network:
          assign_public_ip: true
        image_id: "{{ item.image }}"
        tags:
          environment: "{{ item.name }}"
      loop:
        - { image: "ami-0360c520857e3138f", name: "manage-node-1" }
        - { image: "ami-0360c520857e3138f", name: "manage-node-2" }
        - { image: "ami-0fd3ac4abb734302a", name: "manage-node-3" }
