---
- hosts: localhost
  connection: local
  vars:
    type: t2.micro

  tasks:
    - name: create ec2 instance
      amazon.aws.ec2_instance:
        name: "ansible-instance"
        instance_type: "{{ type }}"
        security_group: default
        image_id: bacdd
        region: us-east-1
        access_key: "{{ ec2_access_key }}"
        secret_key: "{{ ec2_secret_key }}"
        network:
          assign_public_ip: true
