---
- hosts: all
  become: true
  tasks:
    - name: check openssh and openssl
      ansible.builtin.package:
        name:
          - openssl
          - openssh
        state: latest
      ignore_errors: yes

    - name: check docker version
      ansible.builtin.command: docker --version
      register: output
      ignore_errors: yes

    - name: install docker
      ansible.builtin.package:
        name: docker.io
        state: present
      when:
       output.failed
